name: project_s
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  equatable: ^2.0.5
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  bot_toast: ^4.0.3
  transparent_image: ^2.0.0
  intl: ^0.17.0
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.1.1
  flutter_local_notifications: ^12.0.3
  firebase_messaging: ^14.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - lib/src/assets/images/
