name: project_s
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  equatable: ^2.0.5
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  bot_toast: ^4.1.3
  transparent_image: ^2.0.1
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  firebase_core: ^3.1.1
  flutter_local_notifications: ^17.2.1+1
  firebase_messaging: ^15.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - lib/src/assets/images/
